version: "2"
services:
  preview:
    build: .
    tty: true
    stdin_open: true
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    volumes:
      - ./data:/data