version: "2"
services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cli
    volumes:
      - ./app:/app
    tty: true
    stdin_open: true
    ports:
      - 3306:3306